### ISSUE TITLE
Create button string empty on nova v3.8.3

### ISSUE THREAD

**Issue by gldrenthe89** [chris-ware/nova-breadcrumbs#104]
On latest nova v3.8.3 the create button string empty. this because in this nova update this is now customisable from within the resource. I had to turn of breadcrumbs in order to get my create button back 😉

**Comment by abishekrsrikaanth** [comment]
I have the same issue as well. Any reason why this package would affect the label of the `Create Button`?

**Comment by chris-ware** [comment]
This is because of the way the version of this package works, due to how Nova operates itself. It overwrites the default views and compiles them into the the breadcrumbs version. It's why there has to be a new version every time Nova releases a major update. I'll re-compile and release a new version later.

Version 2 removes this requirement, but its not quite ready yet.

**Comment by chris-ware** [comment]
I've just released 1.3.9 to hopefully solve this issue.
