### ISSUE TITLE
When filter is reset bread crumb is not working

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [chris-ware/nova-breadcrumbs#109]
![video-to-gif-converter](https://user-images.githubusercontent.com/42089253/95425405-0cbd9f80-0966-11eb-8681-af8c39fa864c.gif)

**Comment by chris-ware** [comment]
@MdMostaFizurRahaman Can you provide a bit more information, ie what version of Nova and what version of breadcrumbs you are using?

**Comment by MdMostaFizurRahaman** [comment]
Nova Version: 3.12.0
nova-breadcrumb Version: ^2.0

**Comment by chris-ware** [comment]
@MdMostaFizurRahaman I've confirmed its an issue, but I haven't had time recently to investigate. I'll get to it as soon as I can.

**Comment by chris-ware** [comment]
@MdMostaFizurRahaman I believe this issue is related to a main issue of Query Strings and how my library interprets them. I've made a number of changes based on several pull requests, to rectify this and will be releasing a new version shortly. Can you let me know if it rectifies your issue? I don't have a suitable test case for this to be able to test myself.
