### ISSUE TITLE
Breadcrumb items to parent item in detail view

### ISSUE THREAD

**Issue by masteruser20** [chris-ware/nova-breadcrumbs#128]
Hi,

Is there any option to have breadcrumbs for parent item when user is on detail page on related item?

For example if we have a HasMany relation table, when user clicks on the item he is redirected to the detail page but there is no breadcrumbs.

(There is breadcrumbs to parent if user clicks on create button)

**Comment by chris-ware** [comment]
There isn't currently simply due to the way Nova works. The reason the breadcrumbs have relationships on some items is that Nova passed viaRelationship query parameters in the URL, so the package is able to read those. Aside from that, there is no other way of being aware of the relationship.

I have some ideas together for a full rebuild of the package which would allow you to customise breadcrumbs to allow for this sort of behaviour, but for many reasons, it isn't a priority for me to work on at the moment.
