### ISSUE TITLE
Nova 4 support please :)

### ISSUE THREAD

**Issue by ewawiktor** [chris-ware/nova-breadcrumbs#131]

**Comment by chris-ware** [comment]
Unfortunately, there is no way currently for this package to be supported by Nova 4, as the mechanic it utilises aren't available. 

Even if they were, I don't currently have the time or access to a Nova 4 site to be able to update this package.

**Comment by ewawiktor** [comment]
Thanks Chris for the quick reply.

**Comment by ianrobertsFF** [comment]
I have just finished the initial release of a Breadcrumbs package for Nova 4, it's a separate package and not a modification of this one for Nova 4. 

You can find it here: https://github.com/Formfeed-UK/nova-breadcrumbs

If someone would rather update this package instead of using mine, you could potentially do it via my [resource cards package](https://github.com/Formfeed-UK/nova-resource-cards) rather than the custom header elements.
