### ISSUE TITLE
broke on 2.0.8

### ISSUE THREAD

**Issue by gaabora** [chris-ware/nova-breadcrumbs#29]
on nova 2.0.8 using of plugin breaks forms

[Vue warn]: Unknown custom element: <form-undefined> 

https://github.com/laravel/nova-issues/issues/1717

**Comment by gaabora** [comment]
For now i notice a change in /nova-api/{resource}/creation-fields response structure: fields now nested in 'fields' attribute of JSON response so that might be a cause.

**Comment by chris-ware** [comment]
As per David Hemphill's response on the issue you posted on nova-issues, ensure compatibility with Nova. The composer version constraints should prevent you from installing this on any version of Nova that is unsupported. I try and rebuild as soon as possible, which is required when changes are made to any of the views, due to the way this package works. I have now rebuilt for 2.0.8. Hopefully, this should resolve this issue.
