### ISSUE TITLE
Duplicating queries when creating/editing resource 

### ISSUE THREAD

**Issue by gaabora** [chris-ware/nova-breadcrumbs#30]
There are duplicating get-fields queries when creating/editing resource (users, for example)
/nova-api/users/creation-fields x2 AJAX requests when creating
/nova-api/users/{resourceId} x2 AJAX requests when editing

**Comment by chris-ware** [comment]
There is nothing I can currently do about this, as the only way to inject the breadcrumbs on anything aside from Index and Details is via custom views that overwrite and include the original view. As consequence, the functions that are run on the original view get run on both the original and the custom view.

I have started work on a new version of the package, but have not had the time to make the necessary pull requests to Nova to allow for custom view headers on all views outside of Index and Detail, to allow for this requirement to be removed. Due to this, I'm going to close this issue as whilst it is still outstanding, there is nothing I can do right at this moment, except for what is already planned.

**Comment by robbykrlos** [comment]
I cannot help wondering why?! why is this package not called "nova-breadcrumbs-duplicated-queries-low-performance"?

It should be there in the title, so that i'm not loosing 2 weeks of investigations searching for what could be the thing that duplicates all calls....

**Comment by gaabora** [comment]
FetchResource.vue mixin has unnecessary call of getResource(), cause all components wich uses this mixin also have the same on mounted so.
