### ISSUE TITLE
Receiving `Nova.missingResource` when accessing index page

### ISSUE THREAD

**Issue by florinmatthew** [chris-ware/nova-breadcrumbs#35]
Works fine on details page, but when accessing index page of a resource, it throws in console:
`TypeError: Nova.missingResource is not a function`
Nova version: ` v1.1.3`
nova-breadcrumbs: `0.7.1`

**Comment by chris-ware** [comment]
If you are stuck on Nova v1 due to not being able to upgrade Laravel to 5.8, I'd suggest upgrading Nova to the last version of Nova v1, which is 1.3.2. 
The pre-Nova v2 version of this package didn't have any specific version constraints, so there may be features and functionality that aren't available in the given version of Nova.
