### ISSUE TITLE
Customizing Resource Label

### ISSUE THREAD

**Issue by anthonywkchan** [chris-ware/nova-breadcrumbs#43]
Chris, thanks so much for your work on this package! We are currently using it on a project and it is indispensable. 

I was wondering if it would be possible to override the URL that's created for the resource Label portion of the Breadcrumb. 

For example, given: `Home / User / 12345` could we customize the URL for "User"? The reason I'm asking is because we have Nova working in sort of a multi-tenant environment. When a user clicks on the "User" breadcrumb, we only want to take them to the users for their company, and not the entire table of users in the database. Any advice on how to modify the URL so that we can send the user to a lens or specific view would be greatly appreciated! 

Anthony

**Comment by chris-ware** [comment]
@anthonywkchan I'm open to suggestions as to how you'd like to be able to do this. At the moment, breadcrumbs are made by using router links based upon the full url string being broken apart. I could make it so that if it identifies a resource, you could overwrite the resource link via the resource itself.

**Comment by chris-ware** [comment]
Unfortunately, I can't see a use case and a way of achieving this right now. The logic for this, in my eyes, would always be elsewhere and the URLs would always just remain the same.
