### ISSUE TITLE
Not supported version

### ISSUE THREAD

**Issue by bernhardh** [chris-ware/nova-breadcrumbs#44]
I have installed Nova v2.1.1 today (fresh laravel and nova copy).

In the docs you write "Current Supported Nova Version: 2.1.1" so it should work, right? But I get

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chris-ware/nova-breadcrumbs 1.2.3 requires laravel/nova >=2.0.0 <=2.1.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.2 requires laravel/nova >=2.0.0 <=2.1.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.1 requires laravel/nova >=2.0.0 <=2.0.11 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.0 requires laravel/nova >=2.0.0 <=2.0.9 -> no matching package found.
```

**Comment by bernhardh** [comment]
Ok, maybe the problem is, that the version of nova has a dev after the number?

```bash
$composer show laravel/nova
name     : laravel/nova
descrip. : A wonderful administration interface for Laravel.
keywords : admin, laravel
versions : * dev-master, 2.1.x-dev
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : []  
dist     : [path] ./nova 78498b6be1221f13339e0ffe6b072e0403d71f79
path     : /home/bernhard/httpdocs/test/laravel/nova/nova
names    : laravel/nova
```

I have installed nova like suggested in the docs with:

```
 "require": {
       ....
        "laravel/nova": "*",
    },
```

**Comment by chris-ware** [comment]
This is not an issue with the package. The package has version constraints, due to overwriting views, as per the comment directly below the current supported version comment.

By using * as the version constraint and what I would guess is the local via a symlink install rather than via proper composer versioning, composer isn't aware of what version of Nova you have installed and therefore cannot decide whether the version is supported or not. Several people have forked this repository themselves to remove this constraint, but that transfers the risk of it not working onto their shoulders. 

You could try the following, but I am going to close this issue as it's not an issue with the package itself.
`"laravel/nova": "* as 2.1.1"`

**Comment by bernhardh** [comment]
I switched now to the composer version. I don't understand, why this isn't the first suggestion on nova documentation, but ok.

Just for others, who find this issue: Setting the version to "2.1.1" doesn't work, since the default version is called something like "2.1.0-dev" or so, which is not compatible.
