### ISSUE TITLE
Nova version issues?

### ISSUE THREAD

**Issue by unarmedwombat** [chris-ware/nova-breadcrumbs#45]
I've just updated Nova to version 2.1.1 and composer update now throws me a 'cannot resolve' error:  
_chris-ware/nova-breadcrumbs 1.2.3 requires laravel/nova >=2.0.0 <=2.1.1 -> no matching package found_
repeated for versions down to 1.2.0. I've confirmed the installed version of Nova is 2.1.1.
I can't see why it won't recognise the Nova 2.1.1 that's installed, so I must be missing something (probably obvius - I'm not a composer expert). Can you point me in the right direction? Thanks.

**Comment by chris-ware** [comment]
Can you confirm how you are installing Nova? If it's via the local install method, rather than via the private packagist repo of Nova, then Nova cannot decide via composer what version is installed, and therefore can't decide what version of this package to resolve for installation. 

See the following issue ([https://github.com/chris-ware/nova-breadcrumbs/issues/44](https://github.com/chris-ware/nova-breadcrumbs/issues/44)) for more information, and a possible solution, however, as this is not an issue with this package, but rather a use of composer issue, I will be closing this issue unless you can provide more information that suggest that my comments on the other issue aren't relevant.
