### ISSUE TITLE
Not Installing In laravel Nova V2.2.0

### ISSUE THREAD

**Issue by jahid56** [chris-ware/nova-breadcrumbs#49]
I could not install the package as it is throws error. I am using NOVA 2.2.0. Here I show my error
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chris-ware/nova-breadcrumbs 1.2.6 requires laravel/nova >=2.0.0 <=2.3.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.5 requires laravel/nova >=2.0.0 <=2.3.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.4 requires laravel/nova >=2.0.0 <=2.2.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.3 requires laravel/nova >=2.0.0 <=2.1.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.2 requires laravel/nova >=2.0.0 <=2.1.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.1 requires laravel/nova >=2.0.0 <=2.0.11 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.0 requires laravel/nova >=2.0.0 <=2.0.9 -> no matching package found.
    - Installation request for chris-ware/nova-breadcrumbs ^1.2 -> satisfiable by chris-ware/nova-breadcrumbs[1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
`

**Comment by chris-ware** [comment]
How are you installing Nova? Is it via a local install or via the private composer repository Nova provides?

**Comment by jahid56** [comment]
I am installing Nova Via Local Install. Here Is my composer.json file for nova
`"laravel/nova": "*",`

**Comment by chris-ware** [comment]
The local install is your issue. Due to the way this package works, it needs to be version constrained. By doing a local install, composer isn't aware of the version of Nova, therefore it cannot determine which version of Breadcrumbs to install. I'd suggest either using the private packagist repo or using one of the forks of this repository that has not got any composer requirements, although I would warn that none of them have updated to support the latest version of Nova.

Closing this issue as it's not an issue with the package.
