### ISSUE TITLE
Can not install package with Laravel Nova 2.9.2

### ISSUE THREAD

**Issue by philipbaginski** [chris-ware/nova-breadcrumbs#72]
Hi!

I try to install package with Laravel Nova 2.9.2, but every time I'm getting error:

composer require chris-ware/nova-breadcrumbs
Using version ^1.2 for chris-ware/nova-breadcrumbs
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - chris-ware/nova-breadcrumbs 1.2.9 requires laravel/nova >=2.0.0 <=2.6.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.8 requires laravel/nova >=2.0.0 <=2.5.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.7 requires laravel/nova >=2.0.0 <=2.4.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.6 requires laravel/nova >=2.0.0 <=2.3.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.5 requires laravel/nova >=2.0.0 <=2.3.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.4 requires laravel/nova >=2.0.0 <=2.2.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.3 requires laravel/nova >=2.0.0 <=2.1.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.2 requires laravel/nova >=2.0.0 <=2.1.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.13 requires laravel/nova >=2.0.0 <=2.9.2 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.12 requires laravel/nova >=2.0.0 <=2.9.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.11 requires laravel/nova >=2.0.0 <=2.8.0 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.10 requires laravel/nova >=2.0.0 <=2.7.1 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.1 requires laravel/nova >=2.0.0 <=2.0.11 -> no matching package found.
    - chris-ware/nova-breadcrumbs 1.2.0 requires laravel/nova >=2.0.0 <=2.0.9 -> no matching package found.
    - Installation request for chris-ware/nova-breadcrumbs ^1.2 -> satisfiable by chris-ware/nova-breadcrumbs[1.2.0, 1.2.1, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Any help?

**Comment by chris-ware** [comment]
How do you have Nova installed? Via the private packagist or via local install?

**Comment by philipbaginski** [comment]
Local install. I use this package with Nova 2.7, but on fresh install of Nova 2.9.2 I have got error as above.

**Comment by chris-ware** [comment]
Duplicate issue, see [#68](https://github.com/chris-ware/nova-breadcrumbs/issues/68)

**Comment by philipbaginski** [comment]
Okay. But why on the same local and with Nova 2.7 it works? What was different?

**Comment by chris-ware** [comment]
There is no difference. Local installs of Nova have never worked with this library since we've introduced version constraints as Composer is not able to detect the version difference. I'm assuming that with your local install, you probably installed breadcrumbs before the version constraints were in place and have been upgrading Nova locally ever since. This would have meant that, in essence, none of the Nova views with Breadcrumbs enabled were being updated. This is essentially one of the main reasons for the version constraints.

**Comment by philipbaginski** [comment]
Okay. I'm asking because I'm newbie with Laravel, Laravel Nova and php. Can you give me any advice how to install this package?

**Comment by chris-ware** [comment]
I'd suggest using the private satis repo: https://nova.laravel.com/docs/2.0/installation.html#installing-nova-via-composer

**Comment by philipbaginski** [comment]
But Nova is already installed. Should I override old files with new installation and I will be able to install package via composer? I istalled your package with Nova 2.7 maybe 2 weeks ago as a test. Few days ago I installed Nova 2.9.2 and package can not be installed.

**Comment by chris-ware** [comment]
I'm not suggesting re-installing, the installation guide gives you all the information required to install via composer via the private satis repo. It's a fairly straightforward switch. Once you've done that, composer will be aware of what version of Nova you have installed. I'm not sure how you managed to install the version for 2.7, as the only thing that has changed since then is an increase in the version constraints. The stricter version constraints were introduced with Nova 2.0, but even then, there have always been constraints on this package.

**Comment by philipbaginski** [comment]
That was my impresion. Nothing changed during two weeks in the code and installing failed. It is the only package not able to be installed by composer.
