### ISSUE TITLE
Problem with last nova version

### ISSUE THREAD

**Issue by inodesrl** [chris-ware/nova-breadcrumbs#81]
Hello,
I tried to install the package on my nova 2.9.3, but I have the problem that attach,
thanks, Marco.
![Cattura](https://user-images.githubusercontent.com/21054404/73923540-52076a00-48cb-11ea-84c2-ed4601e73959.JPG)

**Comment by chris-ware** [comment]
Are you running nova as a local install? If so, please see #68

**Comment by inodesrl** [comment]
I have installed nova downloading the zip file.
But now for me is a problem to reinstall nova !
Is there another trick to solve the problem ?
thanks !

**Comment by philipbaginski** [comment]
It is the only package that I'm not able to install on local :-) The only one 👎 Why?

**Comment by chris-ware** [comment]
To be honest, if you read the comments, on every issue that has been raised on this, you should understand why. 

Let me break this down simply:

* This package has a reliance on Nova. Most packages either don't bother with this reliance or simply put laravel/nova:* as the requirement. This is because they don't have anything that relies on specific versions of Nova or just don't care.
* Due to the way this package works, we **overwrite default views**. It's the only way to get the breadcrumbs injected onto the Vue templates. Nova 2.7 added extra custom headers after I added an issue for it, but not to every view, so even if I could use those (which I have a WIP version 2 of this package with this support in), the few views that don't have the custom headers will still need original Vue files being overwritten.
* As each version of Nova could potentially make a change to the view, instead of simply not caring about that and then having everyone moan at me or at the Nova devs that stuff that should be fixed simply isn't, I version lock the package to the latest compiled version of Nova, thus ensuring that the views I overwrite match the views for which Nova is using and therefore ensuring that all bugs/new features Nova releases with each passing version are in with the breadcrumbs.
* Local install with initially the only way Nova could be installed, but since then Nova is available via private satis repo. This is the advised approach for many reasons. With local install, there is no way to declare the version of the package you have installed, thus allowing other packages with reliance to compare version requirements.
* If anyone have issues with the above, then maybe try reaching out to the Nova devs, and finding out why they didn't add breadcrumbs in the first place or when it was requested several times. If memory serves me correct, Taylor Otwell said that people could just use the back button, and there is a branch stashed away in the Nova repo that has breadcrumbs in. Or try coding this yourself in a better way. I've spent countless hours on this, with no financial or other reward, so the fact that I still maintain this shows I have some care for the open source community.

I'm going to pin this issue or copy this and make a new pinned issue that hopefully deters people for constantly asking this question. I'm between a rock and a hard place on this, and I'm choosing to put up with this, rather than have the Nova devs be faced with the same constant questions of why fixes haven't been applied, why new features can't be accessed or why something isn't working as expected.

**Comment by philipbaginski** [comment]
Now! Now it's extremaly clear, and we finally know why this very good package does not install on local and why (the most important question for newbies like me). I would like to say: Thank you so much for your explanation 👍 Keep coding :-)

**Comment by inodesrl** [comment]
Thanks very much !
