### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by thibodelanghe** [chris-ware/nova-breadcrumbs#89]
Nova version => 2.3.*
breadcrumbs version => 1.2.20
Breadcrumbs is registered in the NovaService Provider and the Breadcrumbs Trait is used in the Resource.php. This error occurs on the index page of a resource. When i try to load a resource the nova front end loads but the table keeps loading

![image](https://user-images.githubusercontent.com/38117009/77051812-2ac4b200-69cc-11ea-94b0-54a2097aab81.png)
![image](https://user-images.githubusercontent.com/38117009/77051830-3021fc80-69cc-11ea-9add-f2e5d283544d.png)

**Comment by chris-ware** [comment]
Have you checked without having breadcrumbs enabled as the code you are looking at in your first screenshot is Nova code rather than the code powering breadcrumbs?

Also, can I ask why you are running Nova 2.3? I know that the package allows it as I left the end dependency as  greater than version 2, but due to views being overwritten, you'll probably find compatibility issues anyway as 1.2.20 is compiled to support Nova 2.11. Ideally, you need to run the version of breadcrumbs that supports the version of Nova you have installed.

**Comment by thibodelanghe** [comment]
> Have you checked without having breadcrumbs enabled as the code you are looking at in your first screenshot is Nova code rather than the code powering breadcrumbs?

Yes, from the moment i add the breadcrumb service provider to the nova service provider all the resources in the CMS break

**Comment by chris-ware** [comment]
I'd suggest updating Nova to the latest version or downgrading Breadcrumbs to the version that matches your Nova install, which would be 1.2.5 or 1.2.6.
